INTERFACE zif_vce_ship_request_model
  PUBLIC .


*  TYPES:
*    BEGIN OF ty_shipcalc_bp,
*      external_id TYPE /scdl/dl_partyno,
*      name1       TYPE char40,
*      name2       TYPE char40,
*      name3       TYPE char40,
*      street      TYPE char60,
*      house_no    TYPE char10,
*      post_code   TYPE char10,
*      city        TYPE char40,
*      country     TYPE char3,
*      reference1  TYPE char10,
*      reference2  TYPE char10,
*    END OF ty_shipcalc_bp,
*
*    BEGIN OF ty_shipcalc_seller,
*      external_id   TYPE /scdl/db_proch_o-vkorg,
*      name          TYPE char10,
*      profit_center TYPE /scdl/db_proci_o-zzvkbur,
*      seller_group  TYPE /scdl/db_proci_o-zzvkgrp,
*    END OF ty_shipcalc_seller,
*
*    BEGIN OF ty_shipcalc_parcels,
*      weight_in_kg         TYPE p LENGTH 8 DECIMALS 3,
*      length_in_cm         TYPE p LENGTH 8 DECIMALS 3,
*      width_in_cm          TYPE p LENGTH 8 DECIMALS 3,
*      height_in_cm         TYPE p LENGTH 8 DECIMALS 3,
*      volume_in_cbm        TYPE p LENGTH 8 DECIMALS 3,
*      net_weight_in_kg     TYPE p LENGTH 8 DECIMALS 3,
*      chargeable_weight    TYPE p LENGTH 8 DECIMALS 3,
*      dimensional_weight   TYPE p LENGTH 8 DECIMALS 3,
*      loading_meters       TYPE p LENGTH 8 DECIMALS 3,
*      lead_time_in_seconds TYPE i,
*    END OF ty_shipcalc_parcels,
*    tt_shipcalc_parcels TYPE STANDARD TABLE OF ty_shipcalc_parcels WITH EMPTY KEY,
*
*    BEGIN OF ty_shipcalc_pallets,
*      weight_in_kg         TYPE p LENGTH 8 DECIMALS 3,
*      length_in_cm         TYPE p LENGTH 8 DECIMALS 3,
*      width_in_cm          TYPE p LENGTH 8 DECIMALS 3,
*      height_in_cm         TYPE p LENGTH 8 DECIMALS 3,
*      volume_in_cbm        TYPE p LENGTH 8 DECIMALS 3,
*      net_weight_in_kg     TYPE p LENGTH 8 DECIMALS 3,
*      chargeable_weight    TYPE p LENGTH 8 DECIMALS 3,
*      dimensional_weight   TYPE p LENGTH 8 DECIMALS 3,
*      loading_meters       TYPE p LENGTH 8 DECIMALS 3,
*      pallet_type          TYPE string,
*      lead_time_in_seconds TYPE i,
*    END OF ty_shipcalc_pallets,
*    tt_shipcalc_pallets TYPE STANDARD TABLE OF ty_shipcalc_pallets WITH EMPTY KEY.

*    BEGIN OF ty_carrier_service,
*      handling_unit_type    TYPE char10,
*      business_partner      TYPE char10,
*      contract              TYPE char10,
*      account               TYPE char10,
*      carma_user_code       TYPE string,
*      service_type          TYPE char10,
*      cut_off_time          TYPE bu_timestamp_t,
*      shipping_cost_in_euro TYPE char10,
*    END OF ty_carrier_service,
*    tt_carrier_service TYPE STANDARD TABLE OF ty_carrier_service WITH EMPTY KEY,

*    BEGIN OF ty_shipment_pickup,
*      pickup_date        TYPE timestamp,
*      preferred_services TYPE tt_carrier_service,
*      services           TYPE tt_carrier_service,
*    END OF ty_shipment_pickup,
*    tt_shipment_pickup TYPE STANDARD TABLE OF ty_shipment_pickup WITH EMPTY KEY.

  TYPES:
*    BEGIN OF ty_shipreq_general,
*      user                TYPE char35,
*      reference           TYPE /scdl/dl_docno_int,
*      reference2          TYPE /scdl/dl_docno_int,
*      reference3          TYPE /scdl/dl_docno_int,
*      reference4          TYPE /scdl/dl_docno_int,
*      incoterms           TYPE /scdl/db_proch_o-inco1,
*      comment             TYPE char255,
*      tpls                TYPE string,
*      services            TYPE string,
*      additional_services TYPE /scwm/tt_string_table,
*      deliver_advice      TYPE char255,
*    END OF ty_shipreq_general,

    BEGIN OF ty_bp,
      external_id TYPE /scdl/dl_partyno,
      name1       TYPE char70,
      name2       TYPE char40,
      name3       TYPE char40,
      name4       TYPE char40,
      street      TYPE char60,
      house_no    TYPE char10,
      post_code   TYPE char10,
      city        TYPE char40,
      state       TYPE char10,
      country     TYPE char3,
      mail        TYPE char10,
      phone       TYPE char10,
      gln         TYPE char10,
      x_coord     TYPE char10,
      y_coord     TYPE char10,
      z_coord     TYPE char10,
    END OF ty_bp,

*    BEGIN OF ty_parameter,
*      key   TYPE char255,
*      value TYPE char255,
*    END OF ty_parameter,
*    tt_parameter TYPE STANDARD TABLE OF ty_parameter WITH EMPTY KEY,

*    BEGIN OF ty_ship_packdata,
*      external_id          TYPE /scdl/db_proch_o-vkorg,
*      length_in_cm         TYPE p LENGTH 8 DECIMALS 3,
*      width_in_cm          TYPE p LENGTH 8 DECIMALS 3,
*      height_in_cm         TYPE p LENGTH 8 DECIMALS 3,
*      weight_in_kg         TYPE p LENGTH 8 DECIMALS 3,
*      content              TYPE char255,
*      type                 TYPE char255,
*      third_party_order_id TYPE char35,
*    END OF ty_ship_packdata,

*    BEGIN OF ty_ship_customer_parameters,
*      label_text      TYPE char255,
*      delivery_note   TYPE char255,
*      identifier_sscc TYPE char255,
*      sscc_number     TYPE char255,
*      identifier_shu  TYPE char255,
*    END OF ty_ship_customer_parameters,

    BEGIN OF ty_packdets_content,
      line_number TYPE char3,
      description TYPE char255,
      weight      TYPE p LENGTH 8 DECIMALS 3,
      quantity    TYPE p LENGTH 8 DECIMALS 3,
    END OF ty_packdets_content,
    tt_packdets_content TYPE STANDARD TABLE OF ty_packdets_content WITH EMPTY KEY,

    BEGIN OF ty_cust_data,
      value             TYPE int8,
      description       TYPE char255,
      currency          TYPE char3,
      code              TYPE char3,
      quantity          TYPE p LENGTH 8 DECIMALS 3,
      country_of_origin TYPE char2,
    END OF ty_cust_data,

    BEGIN OF ty_dangergoods,
      classification     TYPE char10,
      number             TYPE i,
      description        TYPE char10,
      uom_value          TYPE i,
      uom                TYPE char3,
      packages_quantity  TYPE char10,
      package_type       TYPE char10,
      package_group      TYPE char10,
      secondary_danger   TYPE char10,
      nos_text           TYPE char10,
      tunnel_code        TYPE char10,
      transport_category TYPE char10,
      factor             TYPE i,
      points             TYPE i,
      notice             TYPE char10,
      type               TYPE char10,
      regulation_set     TYPE char10,
      transport_mode     TYPE char1,
    END OF ty_dangergoods,
*    tt_shipreq_dangergoods TYPE STANDARD TABLE OF ty_shipreq_dangergoods WITH EMPTY KEY,

    BEGIN OF ty_packdetails,
      line_number     TYPE char1,
      article_number  TYPE char10,
      description     TYPE char10,
      po_line_number  TYPE char2,
      length          TYPE p LENGTH 8 DECIMALS 3,
      width           TYPE p LENGTH 8 DECIMALS 3,
      height          TYPE p LENGTH 8 DECIMALS 3,
      weight          TYPE p LENGTH 8 DECIMALS 3,
      quantity        TYPE p LENGTH 8 DECIMALS 3,
      parameters      TYPE zif_vce_api_model=>tt_parameter,
      customs_data    TYPE ty_cust_data,
      dangerous_goods TYPE ty_dangergoods,
*      content         TYPE tt_ship_packdets_content,
*      customer        TYPE ty_ship_packdets_cust_data,
*      dangerous_goods TYPE tt_ship_packdets_dangergoods,
    END OF ty_packdetails,
    tt_packdetails TYPE STANDARD TABLE OF ty_packdetails WITH EMPTY KEY,

    BEGIN OF ty_packages_response,
      order_no              TYPE /scdl/db_proch_o-docno,
      status                TYPE i,
      status_desc           TYPE char35,
      tracking_no           TYPE /scdl/db_proch_o-docno,
      external_id           TYPE char35,
      reference             TYPE char35,
      pdf_label_data        TYPE fpcontent,
      zpl_label_data        TYPE fpcontent,
      return_tracking_no    TYPE char35,
      return_pdf_label_data TYPE xstring,
      return_zpl_label_data TYPE xstring,
      label_format          TYPE char10,
    END OF ty_packages_response,
    tt_packages_response TYPE STANDARD TABLE OF ty_packages_response WITH EMPTY KEY,

    BEGIN OF ty_packages_request,
      external_id          TYPE char255,
      reference            TYPE /scdl/dl_docno_int,
      reference2           TYPE /scdl/dl_docno_int,
      reference3           TYPE /scdl/dl_docno_int,
      length               TYPE p LENGTH 8 DECIMALS 3,
      width                TYPE p LENGTH 8 DECIMALS 3,
      height               TYPE p LENGTH 8 DECIMALS 3,
      weight               TYPE p LENGTH 8 DECIMALS 3,
      content              TYPE char10,
      type                 TYPE char10,
      cash_currency        TYPE char10,
      cash_value           TYPE char10,
      third_party_order_id TYPE char10,
      package_count        TYPE char1,
      package_count_total  TYPE i,
      parameters           TYPE zif_vce_api_model=>tt_parameter,
      package_details      TYPE tt_packdetails,
    END OF ty_packages_request,
    tt_packages_request TYPE STANDARD TABLE OF ty_packages_request WITH EMPTY KEY.

  TYPES:
    BEGIN OF ty_ship_request,
      user                TYPE char35,
      reference           TYPE /scdl/dl_docno_int,
      reference2          TYPE /scdl/dl_docno_int,
      reference3          TYPE /scdl/dl_docno_int,
      reference4          TYPE /scdl/dl_docno_int,
      incoterms           TYPE /scdl/db_proch_o-inco1,
      comment             TYPE char255,
      tpls                TYPE /scwm/tt_string_table,
      services            TYPE /scwm/tt_string_table,
      additional_services TYPE /scwm/tt_string_table,
      deliver_advice      TYPE char255,
      sender              TYPE ty_bp,
      receiver            TYPE ty_bp,
      cover_address       TYPE ty_bp,
      additional_address  TYPE ty_bp,
      return_address      TYPE ty_bp,
      parameters          TYPE zif_vce_api_model=>tt_parameter,
      packages            TYPE tt_packages_request,
    END OF ty_ship_request,

*    BEGIN OF ty_request,
*      ship_request TYPE ty_ship_request,
*    END OF ty_request,

    ty_request TYPE ty_ship_request,

    tt_request TYPE STANDARD TABLE OF ty_request WITH EMPTY KEY.

  TYPES:
    BEGIN OF ty_response,
      error              TYPE char10,
      error_desc         TYPE string,
      master_tracking_no TYPE /scdl/db_proch_o-docno,
      carma_id           TYPE int8,
      parameters         TYPE zif_vce_api_model=>tt_parameter,
      packages           TYPE tt_packages_response,
    END OF ty_response.

ENDINTERFACE.
